/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-12-21 03:59:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class craw_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\n");
      out.write("    \n");
      out.write("    <title>My JSP 'craw.jsp' starting page</title>\n");
      out.write("    \n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\n");
      out.write("\t<!--\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\n");
      out.write("\t-->\n");
      out.write("\n");
      out.write("  </head>\n");
      out.write("  \n");
      out.write("  <body>\n");
      out.write("    <a href=\"news/AddNBANewsAction\">录入nba新闻［腾讯，新浪，tbba，NBA98］</a>&nbsp;&nbsp;&nbsp;<a href=\"http://sports.qq.com/l/basket/nba/newsmore.htm\" target=\"_blank\">address</a><br><br>\n");
      out.write("      <a href=\"news/AddZhiBoBaNews\">录入nba新闻［直播吧］</a><br><br><br><br>\n");
      out.write("      \n");
      out.write("     <a href=\"news/AddCBANewsAction\">录入cba新闻[搜狐，新浪，新华]</a>&nbsp;&nbsp;&nbsp;<a href=\"http://roll.sports.sina.com.cn/s_campusbasket_all/index.shtml\" target=\"_blank\">address</a><br><br>\n");
      out.write("     \n");
      out.write("      <a href=\"news/AddTencentCBANews\">录入cba新闻[腾讯]</a>&nbsp;&nbsp;&nbsp;<a href=\"http://sports.qq.com/l/cba/CBAlist.htm\" target=\"_blank\">address</a><br><br> \n");
      out.write("\n");
      out.write("    <a href=\"news/AddNBAVideoAction\">录入新浪nba视频</a><br><br>\n");
      out.write("    \n");
      out.write("  <a href=\"news/AddNBA98Video\">录入NBA98 nba视频</a><br><br>    \n");
      out.write("  \n");
      out.write("    <a href=\"news/AddLETVVideoAction\">录入LETV</a><br><br>\n");
      out.write(" \n");
      out.write("    <a href=\"news/AddHuPuVideoAction\">录入虎扑视频</a><br><br>\n");
      out.write("    \n");
      out.write("  <!--     \n");
      out.write("     <a href=\"news/AddEurope\">录入Europe新闻[搜狐］</a><br><br>\n");
      out.write("    <a href=\"news/AddWCBA\">录入WCBA新闻［腾讯］</a><br><br><br><br>\n");
      out.write("         \n");
      out.write("     <a href=\"news/AddZhiBoBaSpecial\">录入直播吧专题</a><br><br><br><br>\n");
      out.write("  \n");
      out.write("   \n");
      out.write("    <a href=\"news/AddNBASoHuAction\">录入nba新闻[搜狐]</a><br><br>\n");
      out.write("   <a href=\"news/AddLuXiangAction\">录入比赛录像</a><br><br>\n");
      out.write("    <a href=\"news/AddDirectAction\">录入比赛直播</a><br><br>\n");
      out.write("     <a href=\"news/AddNBAMatchResultAction\">录入NBA比赛结果［新浪］</a><br><br>\n");
      out.write("    <a href=\"news/AddCBAMatchResultAction\">录入CBA比赛结果［新浪］</a><br><br>\n");
      out.write("  -->\n");
      out.write("     <a href=\"news/AddFalseUser\">录入用户</a><br><br>\n");
      out.write("    \n");
      out.write("\n");
      out.write("    \n");
      out.write("    \n");
      out.write("     \n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
