/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-12-21 04:01:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class downloadimg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\n");
      out.write("    \n");
      out.write("    <title>新闻编辑</title>\n");
      out.write("    \n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\n");
      out.write("\t<!--\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\n");
      out.write("\t-->\n");
      out.write("\t<script charset=\"utf-8\" src=\"${pageContext.request.contextPath}/kindeditor4/kindeditor.js\"></script>\n");
      out.write("\t<script charset=\"utf-8\" src=\"${pageContext.request.contextPath}/kindeditor4/zh_CN.js\"></script>\n");
      out.write("\t <script type=\"text/javascript\" src=\"js/jquery-1.7.2.js\"></script>\n");
      out.write("\t <script type=\"text/javascript\">\n");
      out.write("\t \n");
      out.write("\t </script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t function updateValue(resourceId,resourceType){\n");
      out.write("\t\t \tvar url = \"recommend/RecommendAction?time=+\"+new Date().getTime()+\"?\";\n");
      out.write("\t\t \t\n");
      out.write("\t\t    \t\t$.get(url, {resourceId: resourceId,resourceType: resourceType},function(data){\n");
      out.write("\t\t    \t\t\t\t \n");
      out.write("\t\t    \t\t\tif (data==\"200\"){\n");
      out.write("\t\t    \t\t\t\t alert(\"推荐成功!\"); \n");
      out.write("\t\t    \t\t\t} else {\t\n");
      out.write("\t\t    \t\t\t\t alert(\"推荐失败!\"); \n");
      out.write("\t\t    \t\t\t}\n");
      out.write("\t\t    \t\t});\n");
      out.write("\t\t }\n");
      out.write("\t</script>\n");
      out.write("\t<script>\n");
      out.write("\t  var editor1=null;\n");
      out.write("\t        KindEditor.ready(function(K) {\n");
      out.write("\t       \n");
      out.write("\t           editor1= K.create('#content', {\n");
      out.write("\t           uploadJson : 'img/UploadToQiNiuAction',\n");
      out.write("\t                \t allowFileManager : true\n");
      out.write("\t                \t });\n");
      out.write("\t           //同步 只有添加此句，才能取到textarea的值\n");
      out.write("               editor1.sync();\n");
      out.write("\n");
      out.write("                 \n");
      out.write("             \n");
      out.write("         \t//editor1.html(\"<p>hello kindeditor</p>\");\n");
      out.write("         \t\n");
      out.write("\t        });\n");
      out.write("\t        \n");
      out.write("\t        function analyze(){\n");
      out.write("\t        \t \n");
      out.write("\t        \tvar source_url=$(\"#source_url\").val();\n");
      out.write("\t\t\t\t  //同步 只有添加此句，才能取到textarea的值\n");
      out.write("               editor1.sync();\n");
      out.write("\t\t\t\t  var f=$(\"#content\").val();\n");
      out.write("\t\t    \t\t\t /* alert(f); */\n");
      out.write("\t\t\t\tvar url = \"video/AnalyzeVideoAction?time=+\"+new Date().getTime()+\"?\";\n");
      out.write("\t\t \t\t\t\n");
      out.write("\t\t    \t\t$.get(url, {videoUrl: source_url},function(data){\n");
      out.write("\t\t    \t\t\t\t \n");
      out.write("\t\t    \t\t\tif (data==\"\"){\n");
      out.write("\t\t    \t\t\t\t alert(\"获取视频失败\"); \n");
      out.write("\t\t    \t\t\t} else {\t\n");
      out.write("\t\t    \t\t\t\n");
      out.write("\t\t    \t\t\t f=f+\"<iframe src=\\\"\"+data+\"\\\" allowfullscreen=\\\"true\\\" scrolling=\\\"no\\\" border=\\\"0\\\" frameborder=\\\"0\\\" style=\\\"min－height:200px;\\\"></iframe>\";\n");
      out.write("\t\t    \t\t\t \n");
      out.write("\t\t    \t\t\t \n");
      out.write("\t\t    \t\t\t editor1.html(f);\n");
      out.write("\t\t    \t\t\t  \n");
      out.write("\t\t    \t\t\t//document.getElementsByTagName(\"content\")[0].contentWindow.document.body.innerHTML = f;\n");
      out.write("\t\t    \t\t\t}\n");
      out.write("\t\t    \t\t});\n");
      out.write("\t        \t\n");
      out.write("\t        }\n");
      out.write("\t</script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(function(){\n");
      out.write("\t\t\t$(\"#videoType\").change(function(){\n");
      out.write("\t\t\tvar source_url=$(\"#source_url\").val();\n");
      out.write("\t\t\tvar recesourceType=$(\"#videoType\").val();\n");
      out.write("\t\t\t\t \n");
      out.write("\t\t\t\tvar url = \"video/AnalyzeVideoAction?time=+\"+new Date().getTime()+\"?\";\n");
      out.write("\t\t \t\t\t\n");
      out.write("\t\t    \t\t$.get(url, {videoUrl: source_url,recesourceType: recesourceType},function(data){\n");
      out.write("\t\t    \t\t\t\t \n");
      out.write("\t\t    \t\t\tif (data==\"\"){\n");
      out.write("\t\t    \t\t\t\t alert(\"获取视频失败\"); \n");
      out.write("\t\t    \t\t\t} else {\t\n");
      out.write("\t\t    \t\t\tvar f=$(\"#content\").val();\n");
      out.write("\t\t    \t\t\t \n");
      out.write("\t\t    \t\t\t $(\"#content\").val(\"ff\");\n");
      out.write("\t\t    \t\t\t \n");
      out.write("\t\t    \t\t\t  \n");
      out.write("\t\t    \t\t\t//document.getElementsByTagName(\"content\")[0].contentWindow.document.body.innerHTML = f;\n");
      out.write("\t\t    \t\t\t}\n");
      out.write("\t\t    \t\t});\n");
      out.write("\t\t    \t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("  </head>\n");
      out.write("  \n");
      out.write("  <body>\n");
      out.write("  <form action=\"download/DownloadImgAction\" name=\"myFrm\" method=\"post\">\n");
      out.write("  图片类型：<select name=\"fileType\" width=\"100px\">\n");
      out.write("  \t<option name=\".gif\" value=\".jpg\" >jpg</option>\n");
      out.write("  \t<option name=\".gif\" value=\".png\" >png</option>\n");
      out.write("  \t<option name=\".gif\" value=\".gif\">gif</option>\n");
      out.write("  </select>\n");
      out.write(" \n");
      out.write(" 图片名称：<input type=\"text\" id=\"fileName\" name=\"fileName\" style=\"width: 300px;height:30px;\"/><br/><br/>\n");
      out.write(" \n");
      out.write(" 图片地址： <input type=\"text\" id=\"sourceUrl\" name=\"sourceUrl\" style=\"width: 300px;height:30px;\"/><br/><br/>\n");
      out.write(" \n");
      out.write("  <input type=\"submit\" value=\"下载图片\" />\n");
      out.write("  \n");
      out.write("\t</form>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
