/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-12-21 03:35:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
 

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>用户登录</title>\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"${pageContext.request.contextPath }/assets/css/reset.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"${pageContext.request.contextPath }/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"${pageContext.request.contextPath}/js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t<script src=\"${pageContext.request.contextPath}/js/jquery.validate.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("    $('.loginbox').css({'position':'absolute','left':($(window).width()-692)/2});\r\n");
      out.write("\t$(window).resize(function(){  \r\n");
      out.write("    $('.loginbox').css({'position':'absolute','left':($(window).width()-692)/2});\r\n");
      out.write("    })  \r\n");
      out.write("});  \r\n");
      out.write("</script> \r\n");
      out.write("<script type=\"text/javascript\">");
      out.write("</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write(" <!-- <body style=\"background-color:#1c77ac; background-image:url(images/light.png); background-repeat:no-repeat; background-position:center top; overflow:hidden;\"> -->\r\n");
      out.write(" <body style=\"background: #91A83E; \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("    <div id=\"mainBody\">\r\n");
      out.write("      <div id=\"cloud1\" class=\"cloud\"></div>\r\n");
      out.write("      <div id=\"cloud2\" class=\"cloud\"></div>\r\n");
      out.write("    </div>  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"logintop\">    \r\n");
      out.write("    <span>欢迎登录后台管理界面平台</span>    \r\n");
      out.write("    <ul>\r\n");
      out.write("    <li><a href=\"#\">回首页</a></li>\r\n");
      out.write("    <li><a href=\"#\">帮助</a></li>\r\n");
      out.write("    <li><a href=\"#\">关于</a></li>\r\n");
      out.write("    </ul>    \r\n");
      out.write("    </div>\r\n");
      out.write(" -->    \r\n");
      out.write("    <!-- \r\n");
      out.write("    <div class=\"loginbody\" style=\"background: transparent;\">\r\n");
      out.write("    \r\n");
      out.write("    <span class=\"systemlogo\"></span> \r\n");
      out.write("      <form action=\"j_spring_security_check\" id=\"login\" name=\"login\"\r\n");
      out.write("\t\t\t\tmethod=\"post\"> \r\n");
      out.write("    <div class=\"loginbox\">\r\n");
      out.write("   \r\n");
      out.write("    <ul>\r\n");
      out.write("    <li>\r\n");
      out.write("    <input name=\"j_username\" id=\"userName\" type=\"text\"  class=\"loginuser\" value=\"${sessionScope['SPRING_SECURITY_LAST_USERNAME']}\"  onclick=\"JavaScript:this.value=''\" />\r\n");
      out.write("   \r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("     <input name=\"j_password\" id=\"userPwd\" type=\"password\" class=\"loginpwd\"  onclick=\"JavaScript:this.value=''\"/>\r\n");
      out.write("       \r\n");
      out.write("    </li>\r\n");
      out.write("    <div style=\"color: red; line-height: 35px;text-align:center;\">\r\n");
      out.write("    \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <li>\r\n");
      out.write("    <input name=\"\" type=\"button\" class=\"loginbtn\" value=\"登录\"  onclick=\"submitForm()\"  />\r\n");
      out.write("     <label><input id=\"_spring_security_remember_me\" name=\"_spring_security_remember_me\" type=\"checkbox\" value=\"true\"/>2周之内免登陆</label>");
      out.write("</li>\r\n");
      out.write("    \r\n");
      out.write("    </ul>\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("     -->\r\n");
      out.write("     \r\n");
      out.write("     <style type=\"text/css\">\r\n");
      out.write("     \t.loginuser, loginpwd { font-size: 30px; font-weight: normal; }\r\n");
      out.write("     \t.loginuser { position: absolute; top: 348px; left: 105px; border: 0; background: transparent; padding: 10px; margin: 0; }\r\n");
      out.write("     \t.loginpwd { position: absolute; top: 432px; left: 105px; border: 0; background: transparent; padding: 10px; margin: 0; }\r\n");
      out.write("     \t.loginbtn{ position: absolute; top: 535px; left: 47px; border: 0; background: transparent; width: 385px; height: 74px; color: transparent; font-size: 0; }\r\n");
      out.write("     </style>\r\n");
      out.write("     <script type=\"text/javascript\">\r\n");
      out.write("     \t$(function() {\r\n");
      out.write("     \t\tvar _fun = function() {\r\n");
      out.write("     \t\t\tvar $this = $(this);\r\n");
      out.write("     \t\t\tif ($.trim($this.val()) == '') {\r\n");
      out.write("     \t\t\t\t$this.css({background: 'transparent'});\r\n");
      out.write("     \t\t\t} else {\r\n");
      out.write("     \t\t\t\t$this.css({background: '#E5E7E9'});\r\n");
      out.write("     \t\t\t}\r\n");
      out.write("     \t\t};\r\n");
      out.write("     \t\t$(\".loginuser, .loginpwd\").each(_fun).bind({'focus, blur, keydown, keyup': _fun});\r\n");
      out.write("     \t\t$('.loginpwd').keydown(function(e) {\r\n");
      out.write("     \t\t\tif (e.which == 13) {\r\n");
      out.write("     \t\t\t\tsubmitForm();\r\n");
      out.write("     \t\t\t}\r\n");
      out.write("     \t\t});\r\n");
      out.write("     \t});\r\n");
      out.write("     \t\r\n");
      out.write("     \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("     </script>\r\n");
      out.write("     \r\n");
      out.write("     <div style=\"background: url('images/login_from.png') no-repeat; width: 479px; height: 639px; margin: 100px auto auto auto; position: relative;\">\r\n");
      out.write("     \t<form action=\"j_spring_security_check\" id=\"myFrm\" name=\"login\" method=\"post\">\r\n");
      out.write("     \t\t <input name=\"j_username\" id=\"userName\" type=\"text\"  class=\"loginuser\" value=\"${sessionScope['SPRING_SECURITY_LAST_USERNAME']}\" />\r\n");
      out.write("     \t\t <input name=\"j_password\" id=\"userPwd\" type=\"password\" class=\"loginpwd\"/>\r\n");
      out.write("     \t\t <input   type=\"submit\" class=\"loginbtn\" value=\"登录\"  />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("     </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- \r\n");
      out.write("    <div class=\"loginbm\">版权所有  【梦想家】2014  <a href=\"http://www.uimaker.com\">www.imengxiangjia.com</a></div>\r\n");
      out.write("     -->\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /admin/login.jsp(107,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(false);
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    \t  用户名或密码错误\r\n");
        out.write("    \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /admin/login.jsp(149,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(false);
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("    \t\talert('用户名或密码错误');\r\n");
        out.write("    \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
