/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2017-12-21 03:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("    <title>My JSP 'left.jsp' starting page</title>\r\n");
      out.write("  \t<link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<script language=\"JavaScript\" src=\"../js/jquery.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery-1.7.2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\t\r\n");
      out.write("\t\t//顶部导航切换\r\n");
      out.write("\t\t$(\".nav li a\").click(function(){\r\n");
      out.write("\t\t\t$(\".nav li a.selected\").removeClass(\"selected\")\r\n");
      out.write("\t\t\t$(this).addClass(\"selected\");\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t})\t\r\n");
      out.write("\t</script>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body style=\"background: #1abc9c  url('images/top_head_houtai.png') no-repeat 188px 16px\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- \r\n");
      out.write("\r\n");
      out.write("    <div class=\"topleft\">\r\n");
      out.write("    <a href=\"main.html\" target=\"_parent\"><img src=\"images/logo.png\" title=\"系统首页\" /></a>\r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("    <ul class=\"nav\">\r\n");
      out.write("    <li><a href=\"default.html\" target=\"rightFrame\" class=\"selected\"><img src=\"images/icon01.png\" title=\"工作台\" /><h2>工作台</h2></a></li>\r\n");
      out.write("    <li><a href=\"imgtable.html\" target=\"rightFrame\"><img src=\"images/icon02.png\" title=\"模型管理\" /><h2>模型管理</h2></a></li>\r\n");
      out.write("    <li><a href=\"imglist.html\"  target=\"rightFrame\"><img src=\"images/icon03.png\" title=\"模块设计\" /><h2>模块设计</h2></a></li>\r\n");
      out.write("    <li><a href=\"tools.html\"  target=\"rightFrame\"><img src=\"images/icon04.png\" title=\"常用工具\" /><h2>常用工具</h2></a></li>\r\n");
      out.write("    <li><a href=\"computer.html\" target=\"rightFrame\"><img src=\"images/icon05.png\" title=\"文件管理\" /><h2>文件管理</h2></a></li>\r\n");
      out.write("    <li><a href=\"tab.html\"  target=\"rightFrame\"><img src=\"images/icon06.png\" title=\"系统设置\" /><h2>系统设置</h2></a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("     -->\r\n");
      out.write("            \r\n");
      out.write("    <div class=\"topright\" style=\"background: transparent;\">    \r\n");
      out.write("    <ul>\r\n");
      out.write("    <!--<li><a href=\"admin/login.jsp\" target=\"_parent\">退出</a></li>  -->\r\n");
      out.write("    </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
